### ISSUE TITLE
YAML seeds fail when Sequel::Model subclass is autoloaded

### ISSUE THREAD

**Issue by mwpastore** [earaujoassis/sequel-seed#11]
If the class specified in a YAML seed is autoloaded (but not yet loaded), Sequel::Seeder.apply will fail with the following error:

```
NameError: undefined local variable or method `class_name' for #<#<Class:0x007fddad16c4b0>:0x007fddaf4f7c68>
```

**Comment by earaujoassis** [comment]
Thank you, @mwpastore, for opening this issue. I'll take a look and send a new version/patch soon.

**Comment by earaujoassis** [comment]
Closing stale issue; error cannot be easily reproduced and doesn't seem to happen often.
