### ISSUE TITLE
Using Arrays in JSON migrations (type mismatch)

### ISSUE THREAD

**Issue by arpitkashyapnestaway** [earaujoassis/sequel-seed#9]
NotificationTemplate.create \
      				  "supported_devices": [1,2,3]   ;
   end# notification do             

it is showing this error
rake aborted!
Sequel::DatabaseError: PG::DatatypeMismatch: ERROR:  column "supported_devices" is of type text[] but expression is of type record
LINE 1: ..._id}', true, 'am_new_owner_lead_email', NULL, '', (1, 2, 3),...

HINT:  You will need to rewrite or cast the expression.

then i have replace [1,2,3] with
 Sequel.pg_array([1,2,3],:text)

error
rake aborted!
Sequel::DatabaseError: PG::InvalidTextRepresentation: ERROR:  malformed array literal: "[1, 2, 3]"
LINE 1: ..._id}', true, 'am_new_owner_lead_email', NULL, '', '[1, 2, 3]...
                                                            
DETAIL:  Missing "]" after array dimensions.

my model class is

require 'sequel'
require 'pg'
require 'sequel/extensions/seed'
Sequel.extension :seed
DB = Sequel.connect(ENV['DATABASE_URL'])

DB.extension :pg_array

class NotificationTemplate < Sequel::Model
  dataset = DB[:notification_templates]
end

i am trying to run using rake db:migrate

**Comment by earaujoassis** [comment]
@arpitkashyapnestaway I'll probably release a new version until Wednesday. I'm really busy these days, so this is still a work in progress. But I'll keep you posted. Thank you ;)

**Comment by earaujoassis** [comment]
I'm currently working on type validation and checking if any side effect could be raised with a new release.

**Comment by ravilakhotia** [comment]
hi @earaujoassis , when can we expect the release ? was thinking of using this extension in production.

**Comment by earaujoassis** [comment]
@ravilakhotia Hi! I'm not really sure when, but I'll keep you posted about a new release. I'm planning to release a fix really soon, since that's affecting most users. Any help is appreciated. Thank you!

**Comment by earaujoassis** [comment]
@arpitkashyapnestaway I've created a new commit for this issue (PR #10). Also, I'd like you to check this spec https://github.com/earaujoassis/sequel-seed/blob/265b16b8baa9c89ed9d9c7c210089ef8870f8944/spec/extensions/seed_with_pg_array_spec.rb As you may see, the `pg_array` extension seems to be working for YAML, JSON and Ruby seeds. Sequel handles `Array` <-> `pg_array` coercion automatically. Please let me know what were your struggles.

**Comment by earaujoassis** [comment]
@ravilakhotia The current version (0.3.2) is good to be used in production. The next version (1.0.0) will deprecate compatibility with ruby 1.9.3 and jruby-1.9mode.
